In [4]:
import numpy as np
import random

### Task 1

In [5]:
a = np.arange (12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Task 2

In [6]:
a1=a.reshape(2, 6)
a2=a.reshape(3, 4)
a3=a.reshape(6, 2)
a4=a.reshape(4, 3)
a5=a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Task 3

In [7]:
a1=a.reshape(2, -1)
a2=a.reshape(3, -1)
a3=a.reshape(-1, 2)
a4=a.reshape(-1, 3)
a5=a.reshape(12, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Task 4

In [10]:
x=np.arange(12, 24)
matr=x.reshape(3,4)
y=matr.reshape(12,1)
print(x)
print(y)
print('The array "y" cannot be called one-dimensional')

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
The array "y" cannot be called one-dimensional


### Task 5

In [12]:
a_r4 = np.random.randn(3,4)
a_r4

array([[ 0.78666125, -1.12256841,  1.41192892, -0.41733867],
       [-0.75176242, -0.57559372,  1.25756294,  0.12187792],
       [-1.41659246,  1.28431036, -0.51062507,  0.89788063]])

In [13]:
print(a_r4.size)
a_r4 = a_r4.flatten()
print(a_r4.size)
a_r4

12
12


array([ 0.78666125, -1.12256841,  1.41192892, -0.41733867, -0.75176242,
       -0.57559372,  1.25756294,  0.12187792, -1.41659246,  1.28431036,
       -0.51062507,  0.89788063])

### Task 6 - 7

In [14]:
a_r5 = np.arange(20, 0, -2)
a_r5

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [15]:
b_r5 = np.arange(20, 1, -2).reshape(1,10)
b_r5

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [16]:
print('The difference between arrays "a_r5" and "b_r5" is that a is one-dimensional, and is two-dimensional')

The difference between arrays "a_r5" and "b_r5" is that a is one-dimensional, and is two-dimensional


### Task 8

In [17]:
a_r6 = np.zeros((2, 2))
a_r6

array([[0., 0.],
       [0., 0.]])

In [18]:
b_r6 = np.zeros((3, 2))+1
b_r6

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
vs = np.vstack((a_r6, b_r6))
vs

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
a_r6.shape, b_r6.shape, vs.shape

((2, 2), (3, 2), (5, 2))

In [24]:
vs.size

10

### Task 9

In [26]:
a_r9 = np.arange(0, 12)
a_r9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
A=a_r9.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
At=A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [29]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [30]:
B.shape

(4, 4)

In [31]:
B_inv=np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

In [32]:
print('It will not be possible to calculate the inverse matrix for matrix B, because it is a degenerate (singular) matrix')

It will not be possible to calculate the inverse matrix for matrix B, because it is a degenerate (singular) matrix


### Task 10-12

In [35]:
np.random.seed(42)
a_r10 = np.random.randint(0, 16, 16)
a_r10

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [36]:
C = a_r10.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [38]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [39]:
d = np.linalg.det(D)
d

-28511999.999999944

In [40]:
r = np.linalg.matrix_rank(D)
r

4

In [41]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

### Task 13

In [42]:
print(B)
print(C)
E = np.where(D_inv==1, B, C)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])