### Task 1

In [12]:
import numpy as np
import statistics

In [50]:
A = np.array([[1, 6], 
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [51]:
mean_0 = format(A.mean(axis=0))
mean_1 = format(A.mean(axis=1))
mean_arr = np.array([mean_0, mean_1])
print(mean_arr)

['[2.  8.4]' '[3.5 5.  7.  6.5 4. ]']


### Task 2

In [62]:
mean_0 = np.mean(A, axis=0)
mean_1 = np.mean(A, axis=1)
a_centered = A - mean_0
print(a_centered)
a_centered.shape

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


(5, 2)

### Task 3

In [77]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [74]:
num_rows, num_cols = A.shape
print(num_rows, num_cols)

5 2


In [76]:
res_task3 = a_centered_sp / (num_rows - 1)
res_task3

2.0

### Task 4

In [78]:
a = A.T
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [79]:
s_c = np.cov(a)
s_c

array([[1. , 2. ],
       [2. , 4.3]])